### PR TITLE
Fixed typo in file Model/CachePurge.php

### PR DESCRIPTION
**Pull request by thespacersm**
Fixed typo $tags1 that should be $tag1

### CODE REVIEW

**Comment by thespacersm** [comment]
Any news?!?

**Comment by thespacersm** [comment]
ANY NEWS???

**Comment by HenKun** [comment]
@thespacersm Did you get any comment on this issue? Seems the project is not mantained?

**Comment by litespeedtech** [comment]
latest release v2.2 addressed this issue.

**Pull request closed without merging**
